version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 14
  build:
    commands:
      - npm install
      - export BUCKET=cf-templates-node-sa-east-1
      - aws cloudformation package --template-file template.yml --s3-bucket cf-templates-node-sa-east-1 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml